export const starterRecipeSeedData = [
  {
    id: 1,
    name: "Chicken Stir Fry",
    description: "Quick chicken and vegetable stir fry for weeknight dinners.",
    instructions:
      "1. Slice chicken breast into strips\n2. Dice bell peppers and slice carrots\n3. Heat oil in a wok over high heat\n4. Cook chicken until golden, about 5 minutes\n5. Add vegetables and stir fry 3-4 minutes\n6. Season with soy sauce and serve over rice",
    prepTimeMinutes: 15,
    cookTimeMinutes: 12,
    servings: 4,
    ingredients: [
      { ingredientName: "chicken breast", quantity: 1.5, unit: "lbs" },
      { ingredientName: "bell peppers", quantity: 2, unit: "count" },
      { ingredientName: "carrots", quantity: 1, unit: "cup" },
      { ingredientName: "spinach", quantity: 2, unit: "cups" },
    ],
  },
  {
    id: 2,
    name: "Yogurt Parfait",
    description: "Layered yogurt with berries and crunchy trail mix.",
    instructions:
      "1. Spoon yogurt into a glass or bowl\n2. Add a layer of berries\n3. Repeat layers\n4. Top with trail mix\n5. Drizzle with honey if desired",
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    ingredients: [
      { ingredientName: "greek yogurt", quantity: 1, unit: "cup" },
      { ingredientName: "berries", quantity: 0.5, unit: "cup" },
      { ingredientName: "trail mix", quantity: 0.25, unit: "cup" },
    ],
  },
  {
    id: 3,
    name: "Classic Grilled Cheese",
    description: "Crispy grilled cheese for using up bread and cheese.",
    instructions:
      "1. Butter two slices of bread on one side\n2. Place cheese between unbuttered sides\n3. Grill in a pan over medium heat\n4. Cook 3-4 minutes per side until golden and cheese melts",
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    servings: 1,
    ingredients: [
      { ingredientName: "bread", quantity: 2, unit: "slices" },
      { ingredientName: "cheddar cheese", quantity: 2, unit: "slices" },
    ],
  },
  {
    id: 4,
    name: "Salmon with Lemon and Herbs",
    description: "Simple baked salmon with lemon and fresh greens.",
    instructions:
      "1. Preheat oven to 400 F\n2. Place salmon on a lined baking sheet\n3. Season with salt, pepper, and herbs\n4. Squeeze lemon juice over the top\n5. Bake for 12-15 minutes until flaky\n6. Serve with spinach or a side salad",
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    servings: 2,
    ingredients: [
      { ingredientName: "salmon", quantity: 0.75, unit: "lbs" },
      { ingredientName: "lemon", quantity: 1, unit: "count" },
      { ingredientName: "spinach", quantity: 3, unit: "cups" },
    ],
  },
  {
    id: 5,
    name: "Chicken Quesadilla",
    description: "Cheesy chicken quesadilla with peppers and sour cream.",
    instructions:
      "1. Shred or dice cooked chicken\n2. Dice bell peppers\n3. Place tortilla in a pan over medium heat\n4. Add cheese, chicken, and peppers to one half\n5. Fold and cook 2-3 minutes per side\n6. Serve with sour cream",
    prepTimeMinutes: 10,
    cookTimeMinutes: 8,
    servings: 2,
    ingredients: [
      { ingredientName: "chicken breast", quantity: 0.5, unit: "lbs" },
      { ingredientName: "tortillas", quantity: 2, unit: "count" },
      { ingredientName: "cheddar cheese", quantity: 0.5, unit: "cup" },
      { ingredientName: "bell peppers", quantity: 1, unit: "count" },
      { ingredientName: "sour cream", quantity: 2, unit: "tbsp" },
    ],
  },
  {
    id: 6,
    name: "Veggie Egg Scramble",
    description: "Fluffy eggs with vegetables and a little cheese.",
    instructions:
      "1. Whisk eggs with a splash of milk\n2. Dice bell peppers and chop spinach\n3. Saute vegetables in butter for 2 minutes\n4. Pour in eggs and gently stir\n5. Cook until just set, about 3 minutes\n6. Season with salt and pepper",
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    servings: 2,
    ingredients: [
      { ingredientName: "eggs", quantity: 4, unit: "count" },
      { ingredientName: "bell peppers", quantity: 1, unit: "count" },
      { ingredientName: "spinach", quantity: 1, unit: "cup" },
      { ingredientName: "cheddar cheese", quantity: 0.25, unit: "cup" },
    ],
  },
  {
    id: 7,
    name: "Carrot Ginger Soup",
    description: "Creamy carrot soup with a warm ginger note.",
    instructions:
      "1. Peel and chop carrots\n2. Saute with onion and ginger\n3. Add vegetable broth and simmer 20 minutes\n4. Blend until smooth\n5. Stir in sour cream and season to taste\n6. Serve with crusty bread",
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 4,
    ingredients: [
      { ingredientName: "carrots", quantity: 1, unit: "bag" },
      { ingredientName: "sour cream", quantity: 3, unit: "tbsp" },
      { ingredientName: "bread", quantity: 4, unit: "slices" },
    ],
  },
  {
    id: 8,
    name: "Garlic Shrimp Pasta",
    description: "Quick garlic shrimp tossed with spaghetti.",
    instructions:
      "1. Cook spaghetti according to package directions\n2. Mince garlic and saute in olive oil\n3. Add shrimp and cook 2-3 minutes per side\n4. Squeeze lemon juice over shrimp\n5. Toss with pasta and season with salt and pepper\n6. Garnish with herbs if available",
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 3,
    ingredients: [
      { ingredientName: "shrimp", quantity: 1, unit: "lbs" },
      { ingredientName: "spaghetti", quantity: 0.5, unit: "box" },
      { ingredientName: "garlic", quantity: 4, unit: "cloves" },
      { ingredientName: "olive oil", quantity: 2, unit: "tbsp" },
      { ingredientName: "lemon", quantity: 1, unit: "count" },
    ],
  },
  {
    id: 9,
    name: "Bacon and Egg Fried Rice",
    description: "Savory fried rice with crispy bacon and scrambled eggs.",
    instructions:
      "1. Cook rice and let it cool\n2. Dice bacon and fry until crispy\n3. Scramble eggs in the same pan, then set aside\n4. Stir-fry rice with garlic and onion\n5. Add back bacon and eggs\n6. Season with soy sauce and serve",
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 3,
    ingredients: [
      { ingredientName: "rice", quantity: 2, unit: "cups" },
      { ingredientName: "bacon", quantity: 4, unit: "slices" },
      { ingredientName: "eggs", quantity: 3, unit: "count" },
      { ingredientName: "garlic", quantity: 2, unit: "cloves" },
      { ingredientName: "onions", quantity: 0.5, unit: "count" },
    ],
  },
  {
    id: 10,
    name: "Apple Cinnamon Yogurt Bowl",
    description: "Greek yogurt topped with apples, honey, and trail mix.",
    instructions:
      "1. Dice apple into small cubes\n2. Spoon yogurt into a bowl\n3. Top with diced apples\n4. Drizzle with honey\n5. Sprinkle trail mix for crunch\n6. Add cinnamon if available",
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    ingredients: [
      { ingredientName: "greek yogurt", quantity: 1, unit: "cup" },
      { ingredientName: "apples", quantity: 1, unit: "count" },
      { ingredientName: "honey", quantity: 1, unit: "tbsp" },
      { ingredientName: "trail mix", quantity: 0.25, unit: "cup" },
    ],
  },
  {
    id: 11,
    name: "Tomato Basil Pasta",
    description: "Bright tomato sauce tossed with spaghetti and fresh basil.",
    instructions:
      "1. Boil spaghetti in salted water\n2. Saute garlic in olive oil until fragrant\n3. Add canned tomatoes and simmer 10 minutes\n4. Season with salt, pepper, and torn basil\n5. Toss with drained pasta\n6. Finish with grated parmesan",
    prepTimeMinutes: 5,
    cookTimeMinutes: 18,
    servings: 3,
    ingredients: [
      { ingredientName: "spaghetti", quantity: 0.5, unit: "box" },
      { ingredientName: "canned tomatoes", quantity: 1, unit: "can" },
      { ingredientName: "garlic", quantity: 3, unit: "cloves" },
      { ingredientName: "basil", quantity: 0.5, unit: "cup" },
      { ingredientName: "olive oil", quantity: 2, unit: "tbsp" },
    ],
  },
  {
    id: 12,
    name: "Avocado Toast",
    description: "Smashed avocado on toasted bread with lemon and pepper.",
    instructions:
      "1. Toast slices of bread until deep golden\n2. Halve and pit the avocado\n3. Smash flesh with lemon juice and salt\n4. Spread thickly on the toast\n5. Crack pepper over the top\n6. Top with a soft-boiled egg if desired",
    prepTimeMinutes: 5,
    cookTimeMinutes: 4,
    servings: 2,
    ingredients: [
      { ingredientName: "bread", quantity: 2, unit: "slices" },
      { ingredientName: "avocado", quantity: 1, unit: "count" },
      { ingredientName: "lemon", quantity: 0.5, unit: "count" },
    ],
  },
  {
    id: 13,
    name: "Tuna Salad Sandwich",
    description: "Classic tuna salad with celery, lemon, and a soft bun.",
    instructions:
      "1. Drain a can of tuna\n2. Mix with mayo, diced celery, and lemon juice\n3. Season with salt and pepper\n4. Pile onto bread or a soft roll\n5. Add lettuce if available\n6. Serve with chips or pickles",
    prepTimeMinutes: 8,
    cookTimeMinutes: 0,
    servings: 2,
    ingredients: [
      { ingredientName: "tuna", quantity: 1, unit: "can" },
      { ingredientName: "bread", quantity: 4, unit: "slices" },
      { ingredientName: "mayo", quantity: 2, unit: "tbsp" },
      { ingredientName: "celery", quantity: 1, unit: "stalk" },
      { ingredientName: "lemon", quantity: 0.5, unit: "count" },
    ],
  },
  {
    id: 14,
    name: "Banana Berry Smoothie",
    description: "Creamy banana, berry, and almond milk smoothie.",
    instructions:
      "1. Peel and break the banana into chunks\n2. Add to blender with berries\n3. Pour in almond milk and a scoop of yogurt\n4. Drizzle in honey\n5. Blend until smooth\n6. Pour over ice and serve",
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 2,
    ingredients: [
      { ingredientName: "banana", quantity: 1, unit: "count" },
      { ingredientName: "berries", quantity: 1, unit: "cup" },
      { ingredientName: "almond milk", quantity: 1, unit: "cup" },
      { ingredientName: "greek yogurt", quantity: 0.5, unit: "cup" },
      { ingredientName: "honey", quantity: 1, unit: "tbsp" },
    ],
  },
  {
    id: 15,
    name: "Hearty Vegetable Soup",
    description: "Brothy soup with carrots, potatoes, onions, and tomatoes.",
    instructions:
      "1. Dice onion, carrots, and potatoes\n2. Saute onion in olive oil until soft\n3. Add carrots, potatoes, and a can of tomatoes\n4. Pour in broth and simmer 25 minutes\n5. Season with salt, pepper, and fresh herbs\n6. Serve with crusty bread",
    prepTimeMinutes: 15,
    cookTimeMinutes: 28,
    servings: 4,
    ingredients: [
      { ingredientName: "carrots", quantity: 3, unit: "count" },
      { ingredientName: "potatoes", quantity: 2, unit: "count" },
      { ingredientName: "onions", quantity: 1, unit: "count" },
      { ingredientName: "canned tomatoes", quantity: 1, unit: "can" },
      { ingredientName: "olive oil", quantity: 2, unit: "tbsp" },
    ],
  },
  {
    id: 16,
    name: "Roasted Sweet Potato Bowl",
    description: "Sweet potatoes, greens, and avocado over rice.",
    instructions:
      "1. Cube sweet potatoes and toss with olive oil, salt, and pepper\n2. Roast at 425 F for 25 minutes\n3. Cook rice while potatoes roast\n4. Wilt spinach in a pan with garlic\n5. Layer rice, potatoes, and greens in bowls\n6. Top with sliced avocado",
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 2,
    ingredients: [
      { ingredientName: "sweet potato", quantity: 2, unit: "count" },
      { ingredientName: "spinach", quantity: 3, unit: "cups" },
      { ingredientName: "rice", quantity: 1, unit: "cup" },
      { ingredientName: "avocado", quantity: 1, unit: "count" },
      { ingredientName: "olive oil", quantity: 2, unit: "tbsp" },
    ],
  },
  {
    id: 17,
    name: "Mushroom Risotto",
    description: "Creamy risotto with seared mushrooms and parmesan.",
    instructions:
      "1. Slice mushrooms and sear in butter until golden\n2. Saute diced onion in olive oil\n3. Stir in rice and toast briefly\n4. Add warm broth one ladle at a time, stirring\n5. Cook 18 minutes until rice is tender\n6. Fold in mushrooms and grated parmesan",
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 3,
    ingredients: [
      { ingredientName: "rice", quantity: 1.5, unit: "cups" },
      { ingredientName: "mushrooms", quantity: 2, unit: "cups" },
      { ingredientName: "onions", quantity: 1, unit: "count" },
      { ingredientName: "parmesan", quantity: 0.5, unit: "cup" },
      { ingredientName: "butter", quantity: 2, unit: "tbsp" },
    ],
  },
  {
    id: 18,
    name: "Lemon Caesar Salad",
    description: "Crisp lettuce with lemony dressing and crouton-style bread.",
    instructions:
      "1. Tear lettuce into bite-size pieces\n2. Cube bread and toast with olive oil for croutons\n3. Whisk lemon juice, olive oil, and grated parmesan\n4. Season dressing with salt and pepper\n5. Toss greens with dressing\n6. Top with croutons and extra parmesan",
    prepTimeMinutes: 10,
    cookTimeMinutes: 8,
    servings: 3,
    ingredients: [
      { ingredientName: "lettuce", quantity: 1, unit: "head" },
      { ingredientName: "bread", quantity: 3, unit: "slices" },
      { ingredientName: "lemon", quantity: 1, unit: "count" },
      { ingredientName: "parmesan", quantity: 0.5, unit: "cup" },
      { ingredientName: "olive oil", quantity: 3, unit: "tbsp" },
    ],
  },
  {
    id: 19,
    name: "Chicken Noodle Soup",
    description: "Comforting chicken soup with carrots and pasta.",
    instructions:
      "1. Dice chicken into bite-size pieces\n2. Saute onion and carrots in a pot\n3. Add chicken and brown briefly\n4. Pour in broth and simmer 15 minutes\n5. Stir in pasta and cook until tender\n6. Season with salt, pepper, and herbs",
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 4,
    ingredients: [
      { ingredientName: "chicken breast", quantity: 1, unit: "lbs" },
      { ingredientName: "carrots", quantity: 2, unit: "count" },
      { ingredientName: "onions", quantity: 1, unit: "count" },
      { ingredientName: "pasta", quantity: 1, unit: "cup" },
    ],
  },
  {
    id: 20,
    name: "Lentil Stew",
    description: "Warm lentil stew with carrots and tomato.",
    instructions:
      "1. Rinse lentils\n2. Saute onion, carrots, and garlic in olive oil\n3. Stir in lentils and canned tomatoes\n4. Add broth and simmer 30 minutes\n5. Season with salt, pepper, and herbs\n6. Serve with crusty bread",
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    servings: 4,
    ingredients: [
      { ingredientName: "lentils", quantity: 1, unit: "cup" },
      { ingredientName: "carrots", quantity: 2, unit: "count" },
      { ingredientName: "onions", quantity: 1, unit: "count" },
      { ingredientName: "canned tomatoes", quantity: 1, unit: "can" },
      { ingredientName: "garlic", quantity: 3, unit: "cloves" },
    ],
  },
  {
    id: 21,
    name: "Berry Yogurt Bowl",
    description: "Greek yogurt with mixed berries, granola, and honey.",
    instructions:
      "1. Spoon yogurt into a wide bowl\n2. Pile fresh berries over the top\n3. Sprinkle a handful of granola\n4. Drizzle with honey\n5. Add chopped nuts for crunch\n6. Eat immediately while granola is crisp",
    prepTimeMinutes: 4,
    cookTimeMinutes: 0,
    servings: 1,
    ingredients: [
      { ingredientName: "greek yogurt", quantity: 1, unit: "cup" },
      { ingredientName: "berries", quantity: 0.75, unit: "cup" },
      { ingredientName: "granola", quantity: 0.25, unit: "cup" },
      { ingredientName: "honey", quantity: 1, unit: "tbsp" },
    ],
  },
  {
    id: 22,
    name: "Pesto Pasta",
    description: "Pasta tossed with basil pesto, garlic, and parmesan.",
    instructions:
      "1. Boil pasta in salted water until al dente\n2. Reserve a cup of pasta water before draining\n3. In a pan, warm olive oil with crushed garlic\n4. Toss pasta with pesto and a splash of pasta water\n5. Stir in grated parmesan\n6. Finish with cracked pepper and torn basil",
    prepTimeMinutes: 5,
    cookTimeMinutes: 12,
    servings: 3,
    ingredients: [
      { ingredientName: "pasta", quantity: 0.5, unit: "box" },
      { ingredientName: "pesto", quantity: 0.5, unit: "cup" },
      { ingredientName: "garlic", quantity: 2, unit: "cloves" },
      { ingredientName: "parmesan", quantity: 0.5, unit: "cup" },
    ],
  },
  {
    id: 23,
    name: "Black Bean Quesadilla",
    description: "Cheesy black bean quesadilla with peppers and lime.",
    instructions:
      "1. Drain and lightly mash black beans\n2. Dice bell peppers and onion\n3. Place tortilla in a hot pan\n4. Layer cheese, beans, peppers, and onion on one half\n5. Fold and cook 2-3 minutes per side\n6. Serve with sour cream and lime wedges",
    prepTimeMinutes: 8,
    cookTimeMinutes: 8,
    servings: 2,
    ingredients: [
      { ingredientName: "tortillas", quantity: 2, unit: "count" },
      { ingredientName: "black beans", quantity: 1, unit: "can" },
      { ingredientName: "cheddar cheese", quantity: 0.5, unit: "cup" },
      { ingredientName: "bell peppers", quantity: 1, unit: "count" },
      { ingredientName: "sour cream", quantity: 2, unit: "tbsp" },
    ],
  },
  {
    id: 24,
    name: "Spinach Feta Omelet",
    description: "Fluffy omelet with wilted spinach and feta.",
    instructions:
      "1. Whisk eggs with a splash of milk\n2. Wilt spinach in butter for 1 minute\n3. Pour in eggs and let edges set\n4. Crumble feta over half the omelet\n5. Fold and cook 1 more minute\n6. Season with salt and pepper",
    prepTimeMinutes: 5,
    cookTimeMinutes: 6,
    servings: 1,
    ingredients: [
      { ingredientName: "eggs", quantity: 3, unit: "count" },
      { ingredientName: "spinach", quantity: 1, unit: "cup" },
      { ingredientName: "feta", quantity: 0.25, unit: "cup" },
      { ingredientName: "butter", quantity: 1, unit: "tbsp" },
    ],
  },
  {
    id: 25,
    name: "Overnight Oats",
    description: "Oats soaked in milk with banana, berries, and honey.",
    instructions:
      "1. Combine oats and milk in a jar\n2. Stir in honey and a pinch of salt\n3. Refrigerate at least 4 hours, ideally overnight\n4. In the morning, top with sliced banana and berries\n5. Add chopped nuts for crunch\n6. Stir and enjoy cold",
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    ingredients: [
      { ingredientName: "oats", quantity: 0.5, unit: "cup" },
      { ingredientName: "almond milk", quantity: 0.75, unit: "cup" },
      { ingredientName: "banana", quantity: 0.5, unit: "count" },
      { ingredientName: "berries", quantity: 0.33, unit: "cup" },
      { ingredientName: "honey", quantity: 1, unit: "tbsp" },
    ],
  },
] as const;
